const education =[
    {
        id:1,
        name:'Machine Learning',
        des:'Machine learning is the study of computer algorithms that can improve automatically through experience and by the use of data. It is seen as a part of artificial intelligence',
        img:'https://upload.wikimedia.org/wikipedia/commons/7/7a/Anatomy-1751201_1280.png',
        price:250
    },
    {
        id:2,
        name:'Algoritham',
        des:'Machine learning is the study of computer algorithms that can improve automatically through experience and by the use of data. It is seen as a part of artificial intelligence',
        img:'https://en.wikipedia.org/wiki/Algorithm#/media/File:Diagram_for_the_computation_of_Bernoulli_numbers.jpg',
        price:250,
    },
    {
        id:3,
        name:'Data Structure',
        des:'Machine learning is the study of computer algorithms that can improve automatically through experience and by the use of data. It is seen as a part of artificial intelligence',
        img:'https://cdn.ttgtmedia.com/rms/onlineimages/whatis-data_structure_mobile.png',
        price:250,
    },
    {
        id:4,
        name:'Operating System',
        des:'Machine learning is the study of computer algorithms that can improve automatically through experience and by the use of data. It is seen as a part of artificial intelligence',
        img:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Operating_system_placement.svg/248px-Operating_system_placement.svg.png',
        price:250,
    },
    {
        id:5,
        name:'Java',
        des:'Machine learning is the study of computer algorithms that can improve automatically through experience and by the use of data. It is seen as a part of artificial intelligence',
        img:'https://pbs.twimg.com/profile_images/1410016948977422337/rKU8iR89_400x400.png',
        price:250,
    },
    {
        id:6,
        name:'Web Development',
        des:'Machine learning is the study of computer algorithms that can improve automatically through experience and by the use of data. It is seen as a part of artificial intelligence',
        img:'https://www.onlinecoursereport.com/wp-content/uploads/2020/07/shutterstock_394793860-1024x784.jpg',
        price:250,
    },
    {
        id:7,
        name:'Business Math',
        des:'Machine learning is the study of computer algorithms that can improve automatically through experience and by the use of data. It is seen as a part of artificial intelligence',
        img:'https://cdn.educba.com/academy/wp-content/uploads/2015/01/Business-Mathematics.jpg',
        price:250,
    },
    {
        id:8,
        name:'Math',
        des:'Machine learning is the study of computer algorithms that can improve automatically through experience and by the use of data. It is seen as a part of artificial intelligence',
        img:'https://miro.medium.com/max/1400/1*L76A5gL6176UbMgn7q4Ybg.jpeg',
        price:250,
    },
    {
        id:9,
        name:'Physics',
        des:'Machine learning is the study of computer algorithms that can improve automatically through experience and by the use of data. It is seen as a part of artificial intelligence',
        img:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/CollageFisica.jpg/450px-CollageFisica.jpg',
        price:250,
    },
    {
        id:10,
        name:'Bangladesh Studies',
        des:'Machine learning is the study of computer algorithms that can improve automatically through experience and by the use of data. It is seen as a part of artificial intelligence',
        img:'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/1200px-Flag_of_Bangladesh.svg.png',
        price:250,
    },
]